### ISSUE TITLE
댓글 입력란 위에 '여기에 파일을 놓아 업로드' 와 '댓글을 입력해 주세요.' 텍스트가 겹쳐 보임

### ISSUE THREAD

**Issue by jihoon-seo** [damoang/theme#63]
제목과 같이, 댓글 입력란 위에 '여기에 파일을 놓아 업로드' 와 '댓글을 입력해 주세요.' 텍스트가 겹쳐 보입니다.

[Windows 11, Google Chrome 123.0.6312.123 (64-bit)]
![image](https://github.com/damoang/theme/assets/46767780/b8e83020-d3b2-4edf-837c-3f024be66661)

[위와 동일한 환경에서 개발자모드로 화면 크기를 400 * 1546 으로 조정]
![image](https://github.com/damoang/theme/assets/46767780/2ba967cc-5f67-43f6-a661-14a673f5c58c)

[Windows 11, Microsoft Edge 123.0.2420.97 (64-bit)]
![image](https://github.com/damoang/theme/assets/46767780/760e8ea4-c3db-4ea8-86b8-651ef6aa7180)

[삼성 One UI 6.1 (Android 14), Google Chrome 123.0.6312.118]
![image](https://github.com/damoang/theme/assets/46767780/b7b9f510-b070-40e8-8562-85f571f43c03)

**Comment by rzglitch** [comment]
브라우저 캐시 때문일 수 있습니다.

강력 새로고침 또는 캐시 삭제 해보시길 바랍니다.

**Comment by jihoon-seo** [comment]
지금 확인해 보니 해결되어서 close 합니다!
